general {
    disable_loading_bar = false
    hide_cursor = true
    grace = 3
    no_fade_in = false
    no_fade_out = false
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/.config/hypr/wallpaper.png
    blur_passes = 3
    blur_size = 7
    brightness = 0.5
    color = rgb(32302f)
}

input-field {
    monitor =
    size = 280, 52
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(504945)
    inner_color = rgb(3c3836)
    font_color = rgb(ebdbb2)
    fade_on_empty = true
    placeholder_text = <i><span foreground="##a89984">Enter password...</span></i>
    check_color = rgb(b8bb26)
    fail_color = rgb(cc241d)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(fabd2f)
    position = 0, -100
    halign = center
    valign = center
    rounding = 8
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    color = rgba(ebdbb2ee)
    font_size = 72
    font_family = 0xProto Nerd Font
    position = 0, 100
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %d %B %Y')"
    color = rgba(a89984cc)
    font_size = 18
    font_family = 0xProto Nerd Font
    position = 0, 30
    halign = center
    valign = center
}
