local ls = require "luasnip"
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("rust_deriv", {
    t "rustPlatform.buildRustPackage {",
    t '\n  pname = "',
    i(1, "name"),
    t '";',
    t '\n  version = "',
    i(2, "0.1.0"),
    t '";',
    t "\n  src = ",
    i(3, "src"),
    t ";",
    t "\n  cargoSha256 = lib.fakeHash;",
    t "\n  nativeBuildInputs = [ ",
    i(4, "pkg-config"),
    t " ];",
    t "\n  buildInputs = [ ",
    i(5),
    t " ];",
    t "\n}",
  }),
  s("lua_deriv", {
    t "stdenv.mkDerivation {",
    t '\n  pname = "',
    i(1, "name"),
    t '";',
    t '\n  version = "',
    i(2, "1.0.0"),
    t '";',
    t "\n  src = ",
    i(3, "src"),
    t ";",
    t "\n  buildInputs = [ lua5_1 ];",
    t "\n  installPhase = ''",
    t "\n    mkdir -p $out/share/lua/5.1",
    t "\n    cp -r . $out/share/lua/5.1/",
    i(4),
    t "\n  '';",
    t "\n}",
  }),
  s("c_deriv", {
    t "stdenv.mkDerivation {",
    t '\n  pname = "',
    i(1, "name"),
    t '";',
    t '\n  version = "',
    i(2, "1.0.0"),
    t '";',
    t "\n  src = ",
    i(3, "src"),
    t ";",
    t "\n  nativeBuildInputs = [ cmake ];",
    t "\n  buildInputs = [ ",
    i(4),
    t " ];",
    t "\n  configurePhase = ''",
    t "\n    cmake -B build -DCMAKE_INSTALL_PREFIX=$out",
    i(5),
    t "\n  '';",
    t "\n  buildPhase = ''",
    t "\n    cmake --build build",
    t "\n  '';",
    t "\n  installPhase = ''",
    t "\n    cmake --install build",
    t "\n  '';",
    t "\n}",
  }),
  s("zig_deriv", {
    t "stdenv.mkDerivation {",
    t '\n  pname = "',
    i(1, "name"),
    t '";',
    t '\n  version = "',
    i(2, "0.11.0"),
    t '";',
    t "\n  src = ",
    i(3, "src"),
    t ";",
    t "\n  nativeBuildInputs = [ zig ];",
    t "\n  buildPhase = ''",
    t "\n    zig build -Doptimize=ReleaseSafe",
    i(4),
    t "\n  '';",
    t "\n  installPhase = ''",
    t "\n    mkdir -p $out/bin",
    t "\n    cp zig-cache/bin/* $out/bin/",
    t "\n  '';",
    t "\n}",
  }),
}
