# Host entrypoint for nixos-p14s.
#
# Dependencies:
# - ../../modules/system (modular system config)
# - ./hardware-configuration.nix (generated by nixos-generate-config)
#
# Customisation notes:
# - Keep machine-specific certificates and stateVersion here.
{...}: {
  imports = [
    ./hardware-configuration.nix
    ../../modules/system
  ];

  nixpkgs.config.allowUnfree = true;

  nix.settings = {
    experimental-features = ["nix-command" "flakes"];
    extra-substituters = [
      "https://the-penwing.cachix.org"
      "https://walker.cachix.org"
      "https://walker-git.cachix.org"
    ];
    extra-trusted-public-keys = [
      "the-penwing.cachix.org-1:b1OsSQhQU/bhmwDiMuStEovsvUIzVPYVfZt289btWAg="
      "walker.cachix.org-1:fG8q+uAaMqhsMxWjwvk0IMb4mFPFLqHjuvfwQxE4oJM="
      "walker-git.cachix.org-1:vmC0ocfPWh0S/vRAQGtChuiZBTAe4wiKDeyyXM0/7pM="
    ];
  };
  nix.optimise = {
    automatic = true;
    dates = "*-*-* 10:00:00";
  };

  nix.gc = {
    automatic = true;
    dates = "*-*-* 10:00:00";
    options = "--delete-older-than 7d";
  };

  nixpkgs.config.permittedInsecurePackages = [
    "electron-39.8.10"
  ];

  security.pki.certificateFiles = [./homelab.crt];

  system.stateVersion = "25.11";
}
