color_theme = "TTY"
theme_background = true
update_ms = 2000
shown_boxes = "cpu mem net proc"
check_temp = true
cpu_sensor = "Auto"
temp_scale = "celsius"
mem_graphs = true
show_swap = true
show_disks = true
disk_free_prct = false
proc_sorting = "cpu lazy"
proc_tree = false
proc_mem_bytes = true
vim_keys = false
net_iface = ""
net_sync = false
