#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(bd93f9ff) rgba(50fa7bff) 45deg
    col.inactive_border = rgba(44475aff)
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 12
    active_opacity = 1.0
    inactive_opacity = 0.92

    shadow {
        enabled = true
        range = 12
        render_power = 2
        color = rgba(1d2021cc)
        color_inactive = rgba(1d202188)
    }

    blur {
        enabled = true
        size = 6
        passes = 2
        vibrancy = 0.1696
        special = true
    }
}

animations {
    enabled = true

    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.35, 0.95
    bezier = snappyBounce, 0.05, 0.9, 0.1, 1.05
    bezier = linear, 0, 0, 1, 1

    animation = windows, 1, 5, snappyBounce, slide
    animation = windowsOut, 1, 4, easeOutQuint, slide
    animation = windowsMove, 1, 4, easeInOutCubic
    animation = border, 1, 10, linear
    animation = borderangle, 1, 30, linear, loop
    animation = fade, 1, 5, easeOutQuint
    animation = workspaces, 1, 5, easeOutQuint, slidevert
    animation = specialWorkspace, 1, 5, snappyBounce, slidevert
}

dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = true
    smart_resizing = true
    force_split = 1
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    focus_on_activate = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    enable_swallow = true
    swallow_regex = ^(ghostty|foot|Alacritty)$
}

cursor {
    no_hardware_cursors = 0
    enable_hyprcursor = true
}

xwayland {
    force_zero_scaling = true
}
