##############################
### WINDOW RULES (0.53+ syntax)
##############################

windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(imv)$, float on
windowrule = match:class ^(easyeffects)$, float on
windowrule = match:title ^(Picture-in-Picture)$, float on

windowrule = match:class ^(org.kde.dolphin)$, size 900 600
windowrule = match:class ^(pavucontrol)$, size 700 450

exec-once = hyprswitch init --show-title &

bind = ALT, Tab, cyclenext
bind = ALT SHIFT, Tab, cyclenext, prev
bind = $mainMod, P, pin

# Select res for sunshine
bind = $mainMod, F1, exec, ~/.local/bin/switch-virtual-res.sh retroid
bind = $mainMod, F2, exec, ~/.local/bin/switch-virtual-res.sh ipad-family
bind = $mainMod, F4, exec, ~/.local/bin/switch-virtual-res.sh off
