# Host entrypoint for nixos-p14s.
#
# Dependencies:
# - ../../modules/system (modular system config)
# - ./hardware-configuration.nix (generated by nixos-generate-config)
#
# Customisation notes:
# - Keep machine-specific certificates and stateVersion here.
{ ... }:

{
  imports = [
    ./hardware-configuration.nix
    ../../modules/system
  ];

  nixpkgs.config.allowUnfree = true;
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nix.optimise = {
    automatic = true;
    dates = "*-*-* 10:00:00";
  };
  nix.gc = {
    automatic = true;
    dates = "*-*-* 10:00:00";
    options = "--delete-older-than 7d";
  };

  security.pki.certificateFiles = [ ./secrets/root.crt ];

  system.stateVersion = "25.11";
}
